spring:
  application:
    name: tlias-web-management
  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true
    #配置分页插件
    pagehelper:
      reasonable: true
      helper-dialect: mysql

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
# 阿里云OSS的配置
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  bucketName: fang-java
  region: cn-beijing
